### ISSUE TITLE
K-mer selection

### ISSUE THREAD

**Issue by yuqing-feng** [nshalon/DomCycle#4]
Hi,

I am confused about the k-mer selection. Is there a guideline about the k-mer selection generated from megahit? I have assembled my metagenomic data with default parameter of megahit (k-mer ranged from 21 to 141). Which one should I choose? The larger the better?

**Comment by eitanyaffe** [comment]
We have tested the tool with k=77 and recommend using that length if possible. Feel free to test other lengths as well -- depending on your assembly and the size-selection during the library preparation you may get different results.

As a rule of thumb, we recommend setting k to roughly a third of the sequenced molecule length. The rationale is as follows. In order to detect cycles that cross over from one contig to another there must be enough read pairs that bridge over a potential k-long overlap between the two consecutive contigs. If the sequenced DNA molecules are long enough (for example, ~500bp) this isn't an issue and k values can be set to the max. However, many protocols produce shorter molecules (200-300bp). In that case setting k=141 will reduce the ability of reads to span over the gap between contigs, and using k=77 would be a more sensible choice.

**Comment by yuqing-feng** [comment]
Thank you for your suggestions.
